import {
    VerticalBox, LineEdit, Button, ScrollView, ComboBox
} from "std-widgets.slint";

import {
    ConfigData
} from "config.slint";

import {
    Item
} from "item.slint";

export component ColoniesView inherits VerticalBox {
    if ConfigData.password_correct: VerticalLayout {
        HorizontalLayout {
            Text {
                text: "Add pod list:";
                vertical-alignment: center;
                horizontal-alignment: left;
            }
            LineEdit {
                horizontal_stretch: 1;
                placeholder_text: "Add pod list address or leave empty to create new...";
            }
            Button {
                text: "Add";
                //clicked => { root.save(); }
            }
        }
        HorizontalLayout{
            Rectangle {
                horizontal-stretch: 1;
            }
            Button {
                text: "Upload All";
            }
            Rectangle {
                horizontal-stretch: 1;
            }
        }
        HorizontalLayout {
            VerticalLayout {
                width: 415px;
                Text {
                    text: "Pod lists";
                }
                Rectangle {
                    border-width: 1px;
                    border-color: #e28743;
                    ScrollView {
                        VerticalLayout {
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                            Item {}
                        }
                    }
                }
            }
            VerticalLayout {
                min-width: 415px;
                Text {
                    text: "Pods";
                }
                Rectangle {
                    border-width: 1px;
                    border-color: #e28743;
                    VerticalLayout {
                        HorizontalLayout {
                            Text {
                                text: "Name:";
                            }
                            LineEdit {
                                placeholder-text: "Enter the pod list name...";
                            }
                        }
                        HorizontalLayout {
                            Text {
                                text: "Select pods:";
                            }
                            ComboBox {
                                current-value: "Default";
                                model: ["Default","Music","Videos","Pictures","Documents"];
                            }
                            Button {
                                text: "Add";
                            }
                        }
                        HorizontalLayout{
                            min-height: 400px;
                            ScrollView {
                                min-width: 415px;
                                Item {
                                    name: "Default";
                                }
                            }
                            VerticalLayout {
                                Button {
                                    text: "Remove";
                                }
                                Rectangle {
                                    vertical-stretch: 1;
                                }
                            }

                        }
                        HorizontalLayout {
                            Rectangle {
                                horizontal-stretch: 1;
                            }
                            Button {
                                text: "Undo Changes";
                            }
                        }
                    }
                }
            }
        }
    }
    if !ConfigData.password_correct: VerticalLayout {
        alignment: center;
            Text {
                text: "Enter password to unlock wallet:";
                vertical-alignment: center;
                horizontal-alignment: center;
            }
            LineEdit {
                text: { ConfigData.current_password };
                height: 30px;
                horizontal_stretch: 1;
                placeholder_text: "Password";
                input-type: password;
                edited(text) => {
                    ConfigData.current_password = text;
                }
                accepted(text) => {ConfigData.unlock_password(text);}
            }
            Button {
                text: "Submit";
                height: 30px;
                clicked => { ConfigData.unlock_password(ConfigData.current_password);
                             if ConfigData.password_correct {
                                 ConfigData.timer_running = true;
                             }
                            }
            }
            Text {
                text: { ConfigData.password_status };
                vertical-alignment: center;
                horizontal-alignment: center;
            }
    }
}
