import {
    VerticalBox, LineEdit, Button
} from "std-widgets.slint";

import {
    ConfigData
} from "config.slint";

export component ColoniesView inherits VerticalBox {
    if ConfigData.password_correct: VerticalLayout {
        Rectangle {
            vertical_stretch: 1;
            horizontal_stretch: 1;
        }
    }
    if !ConfigData.password_correct: VerticalLayout {
        alignment: center;
            Text {
                text: "Enter password to unlock wallet:";
                vertical-alignment: center;
                horizontal-alignment: center;
            }
            LineEdit {
                text: { ConfigData.current_password };
                height: 30px;
                horizontal_stretch: 1;
                placeholder_text: "Password";
                input-type: password;
                edited(text) => {
                    ConfigData.current_password = text;
                }
                accepted(text) => {ConfigData.unlock_password(text);}
            }
            Button {
                text: "Submit";
                height: 30px;
                clicked => { ConfigData.unlock_password(ConfigData.current_password);
                             if ConfigData.password_correct {
                                 ConfigData.timer_running = true;
                             }
                            }
            }
            Text {
                text: { ConfigData.password_status };
                vertical-alignment: center;
                horizontal-alignment: center;
            }
    }
}
