import {
    GridBox, LineEdit, Button
} from "std-widgets.slint";

export global ConfigData {
    callback save_config(string, string, string);
    callback change_password();
    callback view_seed_phrase();
    in-out property <int> password_timeout: 0;
    in-out property <string> download_path: "";
    in-out property <string> data_path: "";
    in-out property <string> seed_phrase: "";
}

export component ConfigView inherits GridBox {
    // Public properties
    GridLayout {
        Row {
            Text {
                text: "Downloads Path:";
                vertical-alignment: center;
                horizontal-alignment: left;
            }
            HorizontalLayout {
                colspan: 3;
                le_download_path := LineEdit {
                    //accepted => { root.reload-manifest(le_manifest.text); }
                    text: ConfigData.download_path;
                    horizontal_stretch: 1;
                }
            }
        }
        Row {
            Text {
                text: "Colony Data Path:";
                vertical-alignment: center;
                horizontal-alignment: left;
            }
            HorizontalLayout {
                colspan: 3;
                le_data_path := LineEdit {
                    //accepted => { root.reload-manifest(le_manifest.text); }
                    text: ConfigData.data_path;
                    horizontal_stretch: 1;
                }
            }
        }
        Row {
            Text {
                text: "Password Timeout:";
                vertical-alignment: center;
                horizontal-alignment: left;
            }
            HorizontalLayout {
                colspan: 1;
                le_password_timeout := LineEdit {
                    //accepted => { root.reload-manifest(le_manifest.text); }
                    input-type: number;
                    text: ConfigData.password_timeout;
                }
            }
        }
    }
    Row {
        Rectangle {
            vertical_stretch: 1;
            horizontal_stretch: 1;
        }
    }
    Row {
        Button {
            text: "Save";
            colspan: 1;
            clicked => { ConfigData.save_config(le_download_path.text, le_data_path.text, le_password_timeout.text); }
        }
    }
    Row {
        HorizontalLayout {
            Text {
            text: "Change Password:";
            vertical-alignment: center;
            horizontal-alignment: left;
        }
            le_change_password_1 := LineEdit {
                horizontal_stretch: 1;
                placeholder_text: "New Password";
                input-type: password;
            }
            le_change_password_2 := LineEdit {
                horizontal_stretch: 1;
                placeholder_text: "Repeat Password";
                input-type: password;
            }
            Button {
                text: "Change";
                clicked => { ConfigData.change_password(); }
            }
        }
    }
    Row {
        HorizontalLayout {
        Text {
            text: "Enter password to view seed phrase:";
            vertical-alignment: center;
            horizontal-alignment: left;
        }
        le_password_view_seed := LineEdit {
            horizontal_stretch: 1;
            placeholder_text: "Password";
            input-type: password;
        }
        Button {
            text: "View Seed Phrase";
            clicked => { ConfigData.view_seed_phrase(); }
        }
    }
    }
    Row {
        Text {
            // Populate the seed phrase here only when this window is in focus and the password as entered
            text: "";
            vertical-alignment: center;
            horizontal-alignment: left;
        }
    }
}
