import {
    VerticalBox, LineEdit, Button
} from "std-widgets.slint";

export component Item inherits Rectangle {

    in-out property <string> name: "some file name";
    in-out property <string> address: "ab7391c0863d48592cba859402348cadfff438291040596dbacd53647dbccef6";
    in-out property <bool> selected: false;
    callback item_selected(string);

    property <color> color_selected: #ffa600;
    property <color> color_unselected: #b69b68;
    property <color> color_on_hover: #ffdea1;

    background: { selected ? color_selected : item_ta.has-hover ? color_on_hover : color_unselected };
    border-radius: 10px;
    drop-shadow-blur: {selected ? 0px : 5px};
    height: 35px;
    width: 400px;

    HorizontalLayout {
        padding-left: 10px;
        padding-bottom: 1px;
        padding-top: 1px;
        VerticalLayout {
            Text {
                text: { name };
                color: #000000;
            }
            Text {
                text: { address };
                font-size: 10px;
                color: #636161;
                TouchArea {
                    clicked => {
                        //FIXME: need to call some kind of rust function to drop this onto the clipboard when clicked
                    }
                }
            }
        }
        Rectangle {
            Image {
                source: @image-url("images/check.svg");
            }
        }
    }
    item_ta := TouchArea {
        enabled: {!selected};
        clicked => {
            //selected = true;
            item_selected(address);
        }
        
    }
}