import { Button, VerticalBox, GridBox, TabWidget } from "std-widgets.slint";

import "fonts/HiBlack-n3a1.otf";

// setup view
import {
    SetupStart, CreateSeedPhrase, ConfirmSeedPhrase, ImportWallet, SetPassword, SetupFinish
} from "setup.slint";

// tabs
import {
    SearchView
} from "search.slint";

import {
    UploadView
} from "upload.slint";

import {
    DownloadView
} from "download.slint";

import {
    ColoniesView
} from "colonies.slint";

import {
    WalletView
} from "wallet.slint";

import {
    ConfigView, ConfigData
} from "config.slint";

export {ConfigData}


export component ColonyUI inherits Window {    
    title: "Colony";
    icon: @image-url("images/logo-96x96.png");
    preferred_width:  1024px;
    preferred_height: 768px;

    // Properties
    in-out property <bool> initial-setup: false;
    in-out property <int> setup-step: 0;

    // Main UI
    VerticalLayout {
        if !root.initial-setup:
            TabWidget {
                Tab {
                    title: "Search";
                    search-view := SearchView {}
                }
                Tab {
                    title: "Uploads";
                    upload-view := UploadView {}
                }
                Tab {
                    title: "Downloads";
                    download-view := DownloadView {}
                }
                Tab {
                    title: "Colonies";
                    colonies-view := ColoniesView {}
                }
                Tab {
                    title: "Wallet";
                    wallet-view := WalletView {}
                }
                Tab {
                    title: "Configuration";
                    config-view := ConfigView {}
                }
            }
        if root.initial-setup && root.setup-step == 0:
            setup-start := SetupStart {}
        if root.initial-setup && root.setup-step == 1:
            create-seed-phrase := CreateSeedPhrase {}
        if root.initial-setup && root.setup-step == 2:
            confirm-seed-phrase := ConfirmSeedPhrase {}
        if root.initial-setup && root.setup-step == 3:
            import-wallet := ImportWallet {}
        if root.initial-setup && root.setup-step == 4:
            set-password := SetPassword {}
        if root.initial-setup && root.setup-step == 5:
            setup-finish := SetupFinish {}
    }  
}
