import { Button, VerticalBox, GridBox, TabWidget, LineEdit } from "std-widgets.slint";

import "fonts/HiBlack-n3a1.otf";

// setup view
import {
    SetupStart, CreateSeedPhrase, ConfirmSeedPhrase, ImportWallet, SetPassword, SetupFinish, SetupData
} from "setup.slint";

// tabs
import {
    SearchView
} from "search.slint";

import {
    UploadView
} from "upload.slint";

import {
    DownloadView
} from "download.slint";

import {
    ColoniesView
} from "colonies.slint";

import {
    WalletView, WalletData
} from "wallet.slint";

import {
    ConfigView, ConfigData
} from "config.slint";

export {ConfigData, SetupData, WalletData}

export global MainData {
}

export component ColonyUI inherits Window {    
    title: "Colony";
    icon: @image-url("images/logo-96x96.png");
    preferred-width:  1024px;
    preferred-height: 768px;

    // Properties
    in-out property <bool> initialized: true;
    in-out property <int> setup-step: 0;

    // Main UI
    VerticalLayout {
        if root.initialized:
            TabWidget {
                Tab {
                    title: "Search";
                    search-view := SearchView {}
                }
                Tab {
                    title: "Uploads";
                    upload-view := UploadView {}
                }
                Tab {
                    title: "Downloads";
                    download-view := DownloadView {}
                }
                Tab {
                    title: "Colonies";
                    colonies-view := ColoniesView {}
                }
                Tab {
                    title: "Wallet";
                    wallet-view := WalletView {}
                }
                Tab {
                    title: "Configuration";
                    config-view := ConfigView {}
                }
            }
        if !root.initialized && root.setup-step == 0:
            setup-start := SetupStart {}
        if !root.initialized && root.setup-step == 1:
            set-password := SetPassword {}
        if !root.initialized && root.setup-step == 2:
            create-seed-phrase := CreateSeedPhrase {}
        if !root.initialized && root.setup-step == 3:
            confirm-seed-phrase := ConfirmSeedPhrase {}
        if !root.initialized && root.setup-step == 4:
            import-wallet := ImportWallet {}
        if !root.initialized && root.setup-step == 5:
            setup-finish := SetupFinish {}
        HorizontalLayout {
            Text {
                text: "Like Colony? Donate ETH or ANT to support development here:";
                vertical-alignment: center;
                font-size: 10px;
                height: 12px;
            }
            donate := LineEdit {
                text: "0xc6e3a7a770656B8473DedCc3d4565b6D507afACE";
                horizontal-alignment: left;
                read-only: true;
                font-size: 10px;
                height: 12px;
                visible: true;
                width: 270px;
            }
            Rectangle {
                height: 12px;
                horizontal-stretch: 1;
            }
        }
    }  
}
