import {
    GridBox, HorizontalBox, Button, LineEdit, ScrollView
} from "std-widgets.slint";

export component SearchView inherits GridBox {
    Row {
        HorizontalLayout {
            colspan: 3;
            Image {
                source: @image-url("images/logo-96x96.png");
                preferred_width:  32px;
                preferred_height: 32px;
            }
            Rectangle {
                width: 5px;
            }
            Text {
                text: "Colony";
                font-family: "Hi.";
                font-weight: 800;
                vertical-alignment: center;
                horizontal-alignment: left;
                font-size: 30px;
                color: #e28743;
            }
            Rectangle {
                width: 15px;
            }
            le_manifest := LineEdit {
                //accepted => { root.reload-manifest(le_manifest.text); }
                horizontal_stretch: 1;
            }
            open_button := Button {
                text: "Search";
                //clicked => { root.show-open-dialog(); }
            }
        }
    }
    Row {
        Rectangle {
            colspan: 4;
            height: 1px;
            background: #e28743;
        }
    }
    Row {
        HorizontalLayout {
            colspan: 4;
            ScrollView {
                vertical_stretch: 1;
            }
            ScrollView {
                vertical_stretch: 1;
            }
        }
    }
}
