import {
    GridBox, Button, LineEdit
} from "std-widgets.slint";

export global SetupData {
    callback inc_setup_step();
    callback dec_setup_step();
    callback finish_setup();
    callback set_password(string,string);
    in-out property <bool> password_result: false;
    in-out property <[string]> seed_phrase: ["","","","","","","","","","","",""];
    in-out property <[string]> confirmation_seed_phrase: ["","","","","","","","","","","",""];
 //   in-out property <[string]> confirmation_seed_phrase <=> seed_phrase; // For debug
    callback generate_seed_phrase();
    callback compare_seed_phrase([string], [string]);
    in-out property <bool> compare_seed_phrase_result: false;
    callback check_seed_phrase_validity([string]);
    in-out property <bool> check_seed_phrase_validity_result: false;
    in-out property <string> ethereum_private_key: "";
    in-out property <string> eth_balance: "";
    in-out property <string> ant_balance: "";
    callback check_ethereum_private_key(string);
    in-out property <bool> check_ethereum_private_key_result: false;
}

export component SetupStart inherits GridBox {
    Row {
        Image {
            source: @image-url("images/logo-192x192.png");
            preferred_width:  150px;
            preferred_height: 150px;
        }
    }
    Row {
        Text {
            text: "Colony";
            font-family: "Hi.";
            font-weight: 800;
            vertical-alignment: center;
            horizontal-alignment: center;
            font-size: 60px;
            color: #e28743;
        }
    }
    Row {
        HorizontalLayout {
            horizontal-stretch: 1;
            Text {
                text: "Welcome! Let's get setup...";
                vertical-alignment: center;
                horizontal-alignment: center;
                font-size: 20px;
            }
            next_button := Button {
                text: "Next";
                height: 30px;
                width: 100px;
                clicked => { SetupData.inc_setup_step(); }
            }
        }
    }
}

export component SetPassword inherits GridBox {
    Row {
        Rectangle {
            vertical_stretch: 1;
            horizontal_stretch: 1;
        }
    }
     Row {
        Text {
            text: "Set   Password";
            font-family: "Hi.";
            font-weight: 800;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 30px;
            color: #e28743;
        }
    }
    Row {
        Text {
            text: "Set a password to encrypt your seed phrase. This will be used to encrypt the seed phrase and private key on your computer. You will need to enter this password every time you want to upload or manage your wallet.";
            wrap: word-wrap;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 12px;
        }
    }
    GridLayout {
        horizontal-stretch: 1;
        Row {
            Text {
                text: "Enter password:";
                horizontal_stretch: 1;
                height: 30px;
            }
            Text {
                text: "Enter password again:";
                horizontal_stretch: 1;
                height: 30px;
            }
        }
        Row {
            le_password1 := LineEdit {
                horizontal_stretch: 1;
                input-type: password;
                height: 30px;
                edited(text) => {
                    SetupData.set_password(le_password1.text, le_password2.text);
                }
            }
            le_password2 := LineEdit {
                horizontal_stretch: 1;
                input-type: password;
                height: 30px;
                edited(text) => {
                    SetupData.set_password(le_password1.text, le_password2.text);
                }
            }
        }
    }
    Row {
        HorizontalLayout {
            horizontal-stretch: 1;
            if SetupData.password_result:
                Text {
                    text: "Password set successfully!";
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    font-size: 20px;
                    color: #00ff00;
                    font-italic: true;
                }
            if !SetupData.password_result:
                Text {
                    text: "Passwords do not match or is not long enough!";
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    font-size: 20px;
                    color: #ff0000;
                    font-italic: true;
                }
        }
    }
    Row {
        HorizontalLayout {
            back_button := Button {
                text: "Back";
                height: 30px;
                clicked => { SetupData.dec_setup_step(); }
            }
            next_button := Button {
                text: "Next";
                height: 30px;
                clicked => { SetupData.inc_setup_step(); }
                enabled: { SetupData.password_result; }
            }
            Rectangle {
                horizontal-stretch: 1;
            }
        }
    } 
}
export component CreateSeedPhrase inherits GridBox {
    Row {
        Rectangle {
            vertical_stretch: 1;
            horizontal_stretch: 1;
        }
    }
    Row {
        Text {
            text: "Create   Seed   Phrase";
            font-family: "Hi.";
            font-weight: 800;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 30px;
            color: #e28743;
        }
    }
    Row {
        Text {
            text: "Enter an existing or generate a new 12 word seed phrase for colony. This will be used to generate the addresses of your colonies so you can find and update them on the Autonomi network.";
            wrap: word-wrap;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 12px;
        }
    }
    Row {
        Text {
            text: "Please MAKE SURE to write down the following seed phrase. You will need it to recover any data you upload using colony. There are no accounts or backups. If you lose your seed phrase, you will lose access to your data.";
            wrap: word-wrap;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 12px;
        }
    }
    Row {
        VerticalLayout {
            for i in [0,1,2]:
                HorizontalLayout {
                    for j in [0,1,2,3]:
                        LineEdit {
                            text: {SetupData.seed_phrase[i*4 + j]};
                            placeholder-text: "seed word " + (i*4 + j + 1);
                            height: 30px;
                            horizontal_stretch: 1;
                            edited(text) => {
                                SetupData.seed_phrase[i*4 + j] = text;
                                SetupData.check_seed_phrase_validity(SetupData.seed_phrase);
                            }
                        }
                    
                }
            
        }
    }
    Row {
        HorizontalLayout {
            regenerate_button := Button {
                text: "Regenerate";
                height: 30px;
                width: 100px;
                clicked => { 
                    SetupData.generate_seed_phrase();
                    SetupData.check_seed_phrase_validity(SetupData.seed_phrase);
                }
            }
            if SetupData.check_seed_phrase_validity_result:
                Text {
                    text: "Seed phrase is valid!";
                    font-italic: true;
                    font-size: 20px;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    color: #00ff00;
                    height: 30px;
                }
            if !SetupData.check_seed_phrase_validity_result:
                Text {
                    text: "Seed phrase contains invalid words or typos!";
                    font-italic: true;
                    font-size: 20px;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    color: #ff0000;
                    height: 30px;
                }
        }
    }
    Row {
        HorizontalLayout {
            back_button := Button {
                text: "Back";
                height: 30px;
                clicked => { SetupData.dec_setup_step(); }
            }
            next_button := Button {
                text: "Next";
                height: 30px;
                enabled: { SetupData.check_seed_phrase_validity_result; }
                clicked => { SetupData.inc_setup_step(); }
            }
            Rectangle {
                horizontal-stretch: 1;
            }
        }
    }

}
export component ConfirmSeedPhrase inherits GridBox {
    Row {
        Rectangle {
            vertical_stretch: 1;
            horizontal_stretch: 1;
        }
    }
    Row {
        Text {
            text: "Confirm   Seed   Phrase";
            font-family: "Hi.";
            font-weight: 800;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 30px;
            color: #e28743;
        }
    }
    Row {
        Text {
            text: "Re-enter the 12 word seed phrase from the last page. This will ensure that nothing was mistyped and that you can recover your data.";
            wrap: word-wrap;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 12px;
        }
    }

    Row {
        VerticalLayout {
            for i in [0,1,2]:
                HorizontalLayout {
                    for j in [0,1,2,3]:
                        LineEdit {
                            text: {SetupData.confirmation_seed_phrase[i*4 + j]};
                            placeholder-text: "seed word " + (i*4 + j + 1);
                            height: 30px;
                            horizontal_stretch: 1;
                            edited(text) => {
                                SetupData.confirmation_seed_phrase[i*4 + j] = text;
                                SetupData.compare_seed_phrase(SetupData.seed_phrase, SetupData.confirmation_seed_phrase);
                            }
                        }
                    
                }
            
        }
    }
    Row {
        HorizontalLayout {
            if SetupData.compare_seed_phrase_result:
                Text {
                    text: "Seed phrase matches!";
                    font-italic: true;
                    font-size: 20px;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    color: #00ff00;
                    height: 30px;
                }
            if !SetupData.compare_seed_phrase_result:
                Text {
                    text: "Seed phrase does not match!";
                    font-italic: true;
                    font-size: 20px;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    color: #ff0000;
                    height: 30px;
                }
        }
    }
    Row {
        HorizontalLayout {
            back_button := Button {
                text: "Back";
                height: 30px;
                clicked => { SetupData.dec_setup_step(); }
            }
            next_button := Button {
                text: "Next";
                height: 30px;
                enabled: { SetupData.compare_seed_phrase_result; }
                clicked => { SetupData.inc_setup_step(); }
            }
            Rectangle {
                horizontal-stretch: 1;
            }
        }
    }

}
export component ImportWallet inherits GridBox {
    Row {
        Rectangle {
            vertical_stretch: 1;
            horizontal_stretch: 1;
        }
    }
    Row {
        Text {
            text: "Import   Ethereum   Wallet";
            font-family: "Hi.";
            font-weight: 800;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 30px;
            color: #e28743;
        }
    }
    Row {
        Text {
            text: "Import the private key from an existing Ethereum wallet. While downloads are free on Autonomi, you will need to pay to upload data to the network. Follow the instructions to extract the private key from your Ethereum wallet.";
            wrap: word-wrap;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 12px;
        }
    }
    Row {
        HorizontalLayout {
        LineEdit {
            text: { SetupData.ethereum_private_key };
            placeholder-text: "Private key";
            height: 30px;
            width: 550px;
            edited(text) => {
                SetupData.ethereum_private_key = text;
                SetupData.check_ethereum_private_key(SetupData.ethereum_private_key);
            }
        }
        Rectangle {
            horizontal-stretch: 1;
        }
        }
    }
    Row {
        HorizontalLayout {
            if SetupData.check_ethereum_private_key_result:
                HorizontalLayout {
                    Text {
                        text: "ETH balance: " + SetupData.eth_balance;
                        font-italic: true;
                        color: #00ff00;
                        height: 30px;
                    }
                    Text {
                        text: "ANT balance: " + SetupData.ant_balance;
                        font-italic: true;
                        color: #00ff00;
                        height: 30px;
                    }
                }
            if !SetupData.check_ethereum_private_key_result:
                Text {
                    text: "Invalid private key!";
                    font-italic: true;
                    color: #ff0000;
                    height: 30px;
                }
        }
    }
    Row {
        HorizontalLayout{
            back_button := Button {
                text: "Back";
                height: 30px;
                clicked => { SetupData.dec_setup_step(); }
            }
            next_button := Button {
                text: "Next";
                height: 30px;
                enabled: { SetupData.check_ethereum_private_key_result; }
                clicked => { SetupData.inc_setup_step(); }
            }
            Rectangle {
                horizontal-stretch: 1;
            }
        }
    }

}
export component SetupFinish inherits GridBox {
    Row {
        Rectangle {
            vertical_stretch: 1;
            horizontal_stretch: 1;
        }
    }
    Row {
        Text {
            text: "Welcome   to   colony";
            font-family: "Hi.";
            font-weight: 800;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 30px;
            color: #e28743;
        }
    }
    Row {
        Text {
            text: "You are all set up! You can now start using colony to upload and manage your data. If you have any questions, please check out the documentation at https://github.com/zettawatt/colony";
            wrap: word-wrap;
            vertical-alignment: top;
            horizontal-alignment: left;
            font-size: 12px;
        }
    }
    Row {
        HorizontalLayout {
            back_button := Button {
                text: "Back";
                height: 30px;
                clicked => { SetupData.dec_setup_step(); }
            }
            next_button := Button {
                text: "Finish";
                height: 30px;
                clicked => { SetupData.finish_setup(); }
            }
            Rectangle {
                horizontal-stretch: 1;
            }
        }
    }

}
